### ISSUE TITLE
Include navigation properties when use Select

### ISSUE THREAD

**Issue by armintodev** [ParsaMehdipour/CleanArchitectureImplementation#1]
موقع استفاده از سلکت نیاز نیست اون رابطه رو اینکلود بزنید چون سلکت از پروجکشن استفاده میکنه مثالش در کد زیر هست

![include](https://user-images.githubusercontent.com/68272602/132952484-7ad4677e-f89a-4db0-89db-39e7beb560e8.png)

البته این نکته هم بگم که هیچ مشکلی نداره که اینکلود زدید چون به روش
 EagerLoading دیتا بارگذاری میشه

اما اگه اینکلود نزنید دیتا به صورت
 SelectLoading بارگذاری میشه

**Comment by ParsaMehdipour** [comment]
مرسی خیلی از توجهتون ممنونم
نکته به جایی بود
